config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "welcome/index"

  root to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :subscribe_user_to_mailing_list

  private

  def subscribe_user_to_mailing_list
    SubscribeUserToMailingListJob.perform_later(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <ul>
    <ul class="nav nav-tabs">
      <li><%= link_to "Terroir", welcome_index_path %></li>
    </ul>
  <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Terroir Coffee</h1>
<p>The World's Premiere Single Origin Coffee Subscription Service</p>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  <form
      id="subscribe-form"
      action="http:////nicholasnadel.us11.list-manage.com/subscribe/post-json?u=5a5baae4f936d9bee5b0b472c&amp;id=378d7bae37"
      method="get">

      <h3>Want more great content delivered to your inbox?</h3>

      <p>(no spam ever, unsubscribe at any time)</p>

      <div>
          <input type="email" placeholder="email *" value="" name="EMAIL" >
          <input type="text" placeholder="first name" value="" name="FNAME">
      </div>

      <div>
          <input type="submit" value="Keep Me Updated" name="subscribe">
      </div>

      <div id="subscribe-result">
      </div>

  </form>


  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

  <script type="text/javascript">
      $(document).ready(function(){
          ajaxMailChimpForm($("#subscribe-form"), $("#subscribe-result"));
          // Turn the given MailChimp form into an ajax version of it.
          // If resultElement is given, the subscribe result is set as html to
          // that element.
          function ajaxMailChimpForm($form, $resultElement){
              // Hijack the submission. We'll submit the form manually.
              $form.submit(function(e) {
                  e.preventDefault();
                  if (!isValidEmail($form)) {
                      var error =  "A valid email address must be provided.";
                      $resultElement.html(error);
                      $resultElement.css("color", "red");
                  } else {
                      $resultElement.css("color", "black");
                      $resultElement.html("Subscribing...");
                      submitSubscribeForm($form, $resultElement);
                  }
              });
          }
          // Validate the email address in the form
          function isValidEmail($form) {
              // If email is empty, show error message.
              // contains just one @
              var email = $form.find("input[type='email']").val();
              if (!email || !email.length) {
                  return false;
              } else if (email.indexOf("@") == -1) {
                  return false;
              }
              return true;
          }
          // Submit the form with an ajax/jsonp request.
          // Based on http://stackoverflow.com/a/15120409/215821
          function submitSubscribeForm($form, $resultElement) {
              $.ajax({
                  type: "GET",
                  url: $form.attr("action"),
                  data: $form.serialize(),
                  cache: false,
                  dataType: "jsonp",
                  jsonp: "c", // trigger MailChimp to return a JSONP response
                  contentType: "application/json; charset=utf-8",
                  error: function(error){
                      // According to jquery docs, this is never called for cross-domain JSONP requests
                  },
                  success: function(data){
                      if (data.result != "success") {
                          var message = data.msg || "Sorry. Unable to subscribe. Please try again later.";
                          $resultElement.css("color", "red");
                          if (data.msg && data.msg.indexOf("already subscribed") >= 0) {
                              message = "You're already subscribed. Thank you.";
                              $resultElement.css("color", "black");
                          }
                          $resultElement.html(message);
                      } else {
                          $resultElement.css("color", "black");
                          $resultElement.html("Thank you!<br>You must confirm the subscription in your inbox.");
                          $resultElement.html("Share with your friends!<br>Facebook Twitter Instagram");

                      }
                  }
              });
          }
      });
  </script>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <button type="button" class="btn btn-primary">Save changes</button>
</div>
</div>
</div>
</div>